### ISSUE TITLE
Uncaught ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/ngx-ow#1]
With the Angular CLI v6 you will get this error.

> Uncaught ReferenceError: Buffer is not defined

The solution is to add the following line to `polyfills.ts`

```ts
import * as buffer from 'buffer';

(window as any).Buffer = buffer;
```

And running

```
yarn add buffer
```

This should be added to the docs.

**Comment by SeifJelidi** [comment]
no fuck you
